-- schema definition ------------------------------------------------
create table role (
	authority varchar(255) not null,
	primary key (authority)
);

create table user (
	id bigint generated by default as identity,
	username varchar(255) not null,
    email varchar(255) not null,
    password varchar(255),
    full_name varchar(255),
    birth_date date,
    joined_at date not null,
    location varchar(255),
    primary key (id)
);

create table user_authorities (
	user_id bigint not null,
    authorities_authority varchar(255) not null
);

create table user_followers (
    user_id bigint not null,
    followers_id bigint not null
);

create table user_following (
    user_id bigint not null,
    following_id bigint not null
);

alter table user 
	drop constraint if exists user_email;
	
alter table user 
	add constraint user_email unique (email);

alter table user
    drop constraint if exists user_username;

alter table user
    add constraint user_username unique (username);

alter table user_followers
    add constraint user_followers_followers_id unique (followers_id);

alter table user_following
    add constraint user_following_following_id unique (following_id);

alter table user_authorities 
	add constraint user_authorities_authority
	foreign key (authorities_authority) 
	references role;
	
alter table user_authorities 
	add constraint user_authorities_user 
	foreign key (user_id) 
	references user;

alter table user_followers
    add constraint user_followers_follower
    foreign key (followers_id)
    references user;

alter table user_followers
    add constraint user_followers_user
    foreign key (user_id)
    references user;

alter table user_following
    add constraint user_following_following
    foreign key (following_id)
    references user;

alter table user_following
    add constraint user_following_user
    foreign key (user_id)
    references user;

-- spring security acl schema ---------------------------------------
create table acl_sid (
    id bigint generated by default as identity(start with 100) not null primary key,
    principal boolean not null,
    sid varchar_ignorecase(100) not null,
    constraint uk_acl_sid unique(sid,principal)
);

create table acl_class (
    id bigint generated by default as identity(start with 100) not null primary key,
    class varchar_ignorecase(500) not null,
    constraint uk_acl_class unique(class)
);

create table acl_object_identity (
    id bigint generated by default as identity(start with 100) not null primary key,
    object_id_class bigint not null,
    object_id_identity bigint not null,
    parent_object bigint,
    owner_sid bigint not null,
    entries_inheriting boolean not null,
    constraint uk_acl_objid
        unique(object_id_class,object_id_identity),
    constraint fk_acl_obj_parent
        foreign key(parent_object) references acl_object_identity(id),
    constraint fk_acl_obj_class
        foreign key(object_id_class) references acl_class(id),
    constraint fk_acl_obj_owner
        foreign key(owner_sid) references acl_sid(id)
);

create table acl_entry (
    id bigint generated by default as identity(start with 100) not null primary key,
    acl_object_identity bigint not null,
    ace_order int not null,
    sid bigint not null,
    mask integer not null,
    granting boolean not null,
    audit_success boolean not null,
    audit_failure boolean not null,
    constraint uk_acl_entry
        unique(acl_object_identity,ace_order),
    constraint fk_acl_entry_obj_id
        foreign key(acl_object_identity) references acl_object_identity(id),
    constraint fk_acl_entry_sid
        foreign key(sid) references acl_sid(id)
);

-- initial data -----------------------------------------------------

insert into role values ('ROLE_CLIENT');
insert into role values ('ROLE_ADMIN');

insert into user (email, username, full_name, password, joined_at)
	values('admin@tuitr.com', 'tuitr', 'Admin Pereira', '$2a$10$3Qrx0rv8qSmZ8s3RlD5qE.upleP7.Qzbg5EoIAm62evEkY4c023TK', '2012-12-12');
insert into user (email, username, full_name, password, joined_at)
	values('client@gmail.com', 'cliente', 'Cliente da Silva', '$2a$10$3Qrx0rv8qSmZ8s3RlD5qE.upleP7.Qzbg5EoIAm62evEkY4c023TK', '2020-10-10');

insert into user_authorities (user_id, authorities_authority)
	values(1,'ROLE_ADMIN');
insert into user_authorities (user_id, authorities_authority) 
	values(2,'ROLE_CLIENT');

-- cliente follows admin --------------------------------------------

insert into user_followers (user_id, followers_id)
    values(1, 2);
insert into user_following (user_id, following_id)
    values(2, 1);